name: Update Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout forked repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Add upstream repository
      run: git remote add upstream https://github.com/technovangelist/videoprojects.git

    - name: Fetch upstream updates
      run: git fetch upstream

    - name: Create new branch with current date
      run: |
        BRANCH_NAME=update-branch-$(date +%Y-%m-%d)
        git checkout -b $BRANCH_NAME

    - name: Merge upstream updates
      run: git merge upstream/main --no-edit

    - name: Push updates to new branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME=update-branch-$(date +%Y-%m-%d)
        git push origin $BRANCH_NAME
